name: Terraform Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate_plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest
      - name: Initialize Terraform
        run: terraform init
      - name: Validate Terraform Configuration
        run: terraform validate
      - name: Plan Terraform Changes
        run: terraform plan -out=plan.out
      - name: Save Plan as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: terraform-plan
          path: plan.out

  apply:
    runs-on: ubuntu-latest
    needs: validate_plan
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest
      - name: Initialize Terraform
        run: terraform init
      - name: Download Plan Artifact
        uses: actions/download-artifact@v2
        with:
          name: terraform-plan
          path: .
      - name: Apply Terraform Changes
        run: terraform apply plan.out
      - name: Cleanup Plan Artifact
        run: rm plan.out

  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest
      - name: Initialize Terraform
        run: terraform init
      - name: Destroy Terraform Resources
        run: terraform destroy -auto-approve
      - name: Cleanup Terraform Files
        run: rm -rf .terraform
